version: "3.1"

services:

    mysql_usuario:
        image: mysql:latest
        container_name: docker-mysql-usuarios
        environment:
            MYSQL_DATABASE: 'db_usuarios'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "6033:3306"
        networks: 
            - prod-network
        expose: 
            - 6033
    mysql_gasto:
        image: mysql:latest
        container_name: docker-mysql-gastos
        environment:
            MYSQL_DATABASE: 'db_gastos'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "6034:3306"
        networks: 
            - prod-network
        expose: 
            - 6034
    mysql_categoria:
        image: mysql:latest
        container_name: docker-mysql-categorias
        environment:
            MYSQL_DATABASE: 'db_categorias'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "6035:3306"
        networks: 
            - prod-network 
        expose: 
            - 6035

networks: 
    prod-network:
        driver: bridge
        