version: "3.1"

services:

    mysql:
        build: 
            dockerfile: ./docker/usuarios-mysql.dockerfile
            context: .
        image: mysql:latest
        container_name: docker-mysql
        environment:
            MYSQL_DATABASE: 'db_usuarios'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: '%'
        ports:
            - "6033:3306"
        networks: 
            - prod-network
networks: 
    prod-network:
        driver: bridge
        